name: Using Conditional Expressions
on: workflow_dispatch
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Run Tests
        run: npm run test
      - name: Output if tests failed
        if: failure()
        run: echo "Tests have failed."
